properties([buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '20')), [$class: 'RebuildSettings', autoRebuild: false, rebuildDisabled: false], [$class: 'JobRestrictionProperty'],
  parameters([
    choice(choices: "eastus\ncanadacentral\nasiapacific\naustraliacentral\neurope\neastus2", description: 'azure region:', name: 'region'),
    choice(choices: "DEV\nQA\nEDU\nSTAGE\nPROD", description: 'Environment:', name: 'ENV'),
    string(defaultValue: 'just my wish', description: 'Jira ticket in  project', name: 'reason'),
    booleanParam(defaultValue: true, description: 'Create new environment after generate', name: 'create_environment'),
    ]),
  pipelineTriggers([])
])

pipeline {
    agent none
    stages {
        stage('Git Clone') {
            steps {
                checkout changelog: false,
                poll: false,
                scm: scmGit(branches: [name: '*/main'],
                extensions: [],
                userRemoteConfigs: [[url: 'https://github.com/IamSatya/Satya_DevOps_Challenge.git']])
            }
        }

        stage('Terraform Action') {
            steps {
		script {
			sh 'terraform init'
              		sh 'terraform validate'
               		sh 'echo "Satya"'
		}
            }
        }

    }
}
