env.TF_VAR_client_id=env.ARM_CLIENT_ID
env.TF_VAR_client_secret=env.ARM_CLIENT_SECRET
env.TF_VAR_tenant_id=env.ARM_TENANT_ID
env.TF_VAR_subscription_id=env.ARM_SUBSCRIPTION_ID

properties([
  parameters([
    choice(choices: "eastus\ncanadacentral\nasiapacific\naustraliacentral\neurope\neastus2", description: 'azure region:', name: 'region'),
    choice(choices: "DEV\nQA\nEDU\nSTAGE\nPROD", description: 'Environment:', name: 'ENV'),
    string(defaultValue: 'satya.fmc.com', description: 'Domain Name', name: 'domainname')
    ])
])
pipeline {
    agent any
    stages {
        stage('Git Clone') {
            steps {
                checkout changelog: false,
                poll: false,
                scm: scmGit(branches: [[name: '*/main']],
                extensions: [],
                userRemoteConfigs: [[url: 'https://github.com/IamSatya/Satya_DevOps_Challenge.git']])
            }
        }

        stage('Terraform Action') {
            steps {
		script {
			load "/var/lib/jenkins/azurecreds"
			dir("infra-challenge/") {
			sh 'terraform init'
              		sh 'terraform validate'
               		sh 'terraform apply -var=domain_name=${domainname} -var=ENV=${ENV} -var=region=${region} -var=client_id="${client_id}" -var=client_secret="${client_secret}" -var=tenant_id="${tenant_id}" -var=subscription_id="${subscription_id}"  --auto-approve'
		}
            }
        }
      }
    }
}
