properties([buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '20')), [$class: 'RebuildSettings', autoRebuild: false, rebuildDisabled: false], [$class: 'JobRestrictionProperty'],
  parameters([
    choice(choices: "eastus\ncanadacentral\nasiapacific\naustraliacentral\neurope\neastus2", description: 'azure region:', name: 'region'),
    choice(choices: "DEV\nQA\nEDU\nSTAGE\nPROD", description: 'Environment:', name: 'ENV'),
    string(defaultValue: 'just my wish', description: 'Jira ticket in  project', name: 'reason'),
    booleanParam(defaultValue: true, description: 'Create new environment after generate', name: 'create_environment'),
    ]),
  pipelineTriggers([])
])

pipeline {
    agent none
    stages {
        stage('Git Clone') {
            steps {
                checkout changelog: false,
                poll: false,
                scm: scmGit(branches: [[name: '*/main']],
                extensions: [],
                userRemoteConfigs: [[url: 'https://github.com/IamSatya/Satya_DevOps_Challenge.git']])
            }
        }

        stage('Terraform Action') {
            steps {
                sh 'terraform init'
                sh 'terraform validate'
                sh 'terraform plan -var=ENV=$ENV -var=region=$region --auto--approve'
            }
        }

        stage('Sequential') {
            stages {
                stage('In Sequential 1') {
                    steps {
                        echo "In Sequential 1"
                    }
                }
                stage('In Sequential 2') {
                    steps {
                        echo "In Sequential 2"
                    }
                }
                stage('Parallel In Sequential') {
                    parallel {
                        stage('In Parallel 1') {
                            steps {
                                echo "In Parallel 1"
                            }
                        }
                        stage('In Parallel 2') {
                            steps {
                                echo "In Parallel 2"
                            }
                        }
                    }
                }
            }
        }
    }
}
